pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'homologacao', url: 'https://github.com/Luan-Kussner/Jenkins.git'
            }
        }

        stage('Deploy local') {
            steps {
                sshagent (credentials: ['2']) {
                    sh '''
                        ssh -o StrictHostKeyChecking=no devcpn1320@localhost << EOF
                            cd /var/www/html/jenkins-exemplo/homologacao-server/app
                            git pull origin homologacao
                        EOF
                    '''
                }
            }
        }
    }
}
